package database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException;
import static errorcontrol.LogManager.writeLog;
import webscraping.RegistryCNMV;

/**
 * Class that manages the access to the database.
 * It works as a interface between database and the program.
 * Open and close connections, insert and retrieve data and check data availability.
 * 
 * @author	Enrique Morales Montero (design, development, documentation)
 * @author	Javier Mora Gonzálbez (mentor and requirements analyst)
 * @author	Carlos Cano Ladera (mentor, guiding with design, development and documentation)
 * @since	29/3/2019
 * @version	5/4/2019
 */
public class DataBaseManager {
	
	// Fields.
	
	private static final String DB_DRIVER = "com.mysql.jdbc.Driver";
	private static final String HOST_AND_PORT = "jdbc:mysql://localhost:3307/cnmv";
	private static final String USER = "admin";
	private static final String PASSWORD = "admin";
	
	/**
	 * Connection object to the database.
	 * It is provided by the driver.
	 */
	private Connection connection;
	
	// Constructors.
	
	/**
	 * DataBaseManager constructor.
	 * No code is needed at this point.
	 * It is only used to instantiate the object.
	 */
	public DataBaseManager() {}
	
	// Methods.
	
	/**
	 * Private procedure that opens the connection to the database.
	 * It uses the mysql driver to establish connections and give them back to the pool of connections.
	 * 
	 * @see DataBaseManager#connection	connection - Treated field.
	 * 
	 * @throws CommunicationsException	DB access error (database closed...)
	 * @throws SQLException				SQL error (user, password...).
	 * @throws ClassNotFoundException	MySQL access driver error.
	 */
	private void openConection() {
		
		try {
			Class.forName(DB_DRIVER);
			connection = DriverManager.getConnection(HOST_AND_PORT, USER, PASSWORD);
		} catch (CommunicationsException e) {
			System.err.println("The database could not be accessed. It may be closed or the port must be controlled...");
			e.printStackTrace();
			writeLog(e, "The database could not be accessed. It may be closed or the port must be controlled...");
		} catch (SQLException e) {
			System.err.println(e.getMessage());
			e.printStackTrace();
			writeLog(e, e.getMessage());
		} catch (ClassNotFoundException e) {
			System.err.println("Class not found. Check the MySQL access driver...");
			e.printStackTrace();
			writeLog(e, "Class not found. Check the MySQL access driver...");
		}
		
	}
	
	/**
	 * Private procedure that closes the connection to the database.
	 * 
	 * @see DataBaseManager#openConection() openConection() - Analogous method.
	 * @see DataBaseManager#connection		connection		- Treated field.
	 * @throws SQLException
	 */
	private void closeConection() {
		
		try {
			connection.close();
		} catch (SQLException e) {
			System.err.println("Exception when closing the database...");
			e.printStackTrace();
			writeLog(e, "Exception when closing the database...");
		}
		
	}
	
	/**
	 * Public function that controls whether the database is empty or not.
	 * 
	 * @return 	<ul>
     * 		<li>True:	The database has registries.</li>
     * 		<li>False:	The database is empty.		</li>
     * 			</ul>
	 * @see DataBaseManager#openConection() openConection() - Necessary method.
	 * 
	 * @throws MySQLSyntaxErrorException	The syntax of the SQL statement must be checked.
	 * @throws SQLException					SQL error.
	 */
	public boolean hasRegistries() {
		
		openConection();												// Connection to the database: open.
		
		String query = "SELECT COUNT(*) FROM financialinfo";			// SQL query.
		
		try {
			
			boolean hasRegistries = false;
			int totalRegistries = 0;
			
			Statement sentence = connection.createStatement();			// The object used for executing a static SQL statementand returning the results it produces.
			ResultSet resul = sentence.executeQuery(query);				// A table of data representing a database result set, which is usually generated by executing a statement that queries the database. 
			
			while (resul.next()) {totalRegistries = resul.getInt(1);}	// The code takes any result.
			if (totalRegistries > 0) {hasRegistries = true;}			// Are there any registries?
			
			resul.close();												// Closing objects and connections.
			sentence.close();
			closeConection();
			
			return hasRegistries;
			
		} catch (MySQLSyntaxErrorException e) {
			closeConection();
			System.err.println("SQL exception when consulting the number of registries that the database contains.");
			System.err.println("The syntax of the SQL statement must be checked.");
			e.printStackTrace();
			writeLog(e, "SQL exception when consulting the number of registries that the database contains. The syntax of the SQL statement must be checked.");
			System.exit(1);
		} catch (SQLException e) {
			closeConection();
			System.err.println("SQL exception when consulting the number of registries that the database contains...");
			e.printStackTrace();
			writeLog(e, "SQL exception when consulting the number of registries that the database contains...");
			System.exit(1);
		}
		
		closeConection();
		
		return false;
	}
	
	/**
	 * The function that collects the last url_info_context stored in the database.
	 * We use this method, and we gather the most recent registry to avoid going through the complete CNMV information because we stop when this information match with a registry in the web site.
	 * In doing so, we dramatically improve the performance of our program in case we deal with a bigger amount of data.
	 * 
	 * @return An String (last url_info_context).
	 * 
	 * @throws MySQLSyntaxErrorException	The syntax of the SQL statement must be checked.
	 * @throws SQLException					SQL error.
	 * 
	 * @see webscraping.Scraper Scraper - For extracting data from the CNMV website.
	 */
	public String getLastUrlInfoContext() {
		
		openConection();											// Connection to the database: open.
		
		String query = "SELECT url_info_context FROM financialinfo ORDER by ID DESC LIMIT 1";
		String lastContext = "NULL";
		
		try {			
			Statement sentence = connection.createStatement();		// The object used to run a static SQL statement and returning the results it produces.		
			ResultSet resul = sentence.executeQuery(query);			// A table of data representing a database result set, which is usually generated by executing a statement that queries the database.
			
			while (resul.next()) {
				lastContext = resul.getString("url_info_context");	// Getting the last url_info_context...
			}
			
			resul.close();											// Closing access objects.
			sentence.close();
			closeConection();
			
			return lastContext;
			
		} catch (MySQLSyntaxErrorException e) {
			closeConection();
			System.err.println("SQL exception when consulting the last registry in the database...");
			System.err.println("The syntax of the SQL statement must be checked.");
			e.printStackTrace();
			writeLog(e, "SQL exception when consulting the last registry in the database. The syntax of the SQL statement must be checked.");
			System.exit(1);
		} catch (SQLException e) {
			closeConection();
			System.err.println("SQL exception when consulting the last registry in the database...");
			e.printStackTrace();
			writeLog(e, "SQL exception when consulting the last registry in the database...");
			System.exit(1);
		}
		
		closeConection();
		
		return lastContext;
	}

	/**
	 * Procedure that stores in the database the new registries of the CNMV, stored in a list.
	 * 
	 * @param list - ArrayList with the new data.
	 * @see DataBaseManager#openConection() openConection() - Necessary method.
	 */
	public void store(ArrayList<RegistryCNMV> list) {
		
		int rowsInserted = 0;
		
		openConection(); 			// Connection to the database: open.
				
		Collections.reverse(list);	// Reverse the list.
		
		// Insertion loop.
		
		System.out.println("\tIns\tMessage");
		
		for (RegistryCNMV registry : list) {
			rowsInserted = storeRegistry(rowsInserted, registry);	// Storing data...
		}
		
		System.out.println("\n\tTOTAL: " + rowsInserted + " insertions.");
		
		closeConection();			// Connection to the database: close.
	}

	/**
	 * Helping method that inserts a row (a record) in the table we keep in the database.
	 * 
	 * @param	rowsInserted	- Counter number.
	 * @param	registry		- Extracted data.
	 * 
	 * @return	Number of rows inserted.
	 * 
	 * @throws SQLException
	 */
	private int storeRegistry(int rowsInserted, RegistryCNMV registry) {
		
		// SQL query.
		
		String query = String.format("INSERT INTO financialinfo (url_ixbrl, url_info_context, entity_name, entity_code, period_end, form, format, hash_code, oam, country) SELECT '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s' FROM dual WHERE NOT EXISTS (SELECT url_info_context FROM financialinfo WHERE url_info_context = '%s') LIMIT 1",
				registry.getUrl_ixbrl(),
				registry.getUrl_info_context(),
				registry.getEntity_name(),
				registry.getEntity_code(),
				registry.getPeriod_end(),
				registry.getForm(),
				registry.getFormat(),
				registry.getHash_code(),
				registry.getOam(),
				registry.getCountry(),
				registry.getUrl_info_context()
				);

		int newRows = 0;

		try {
			Statement sentence = connection.createStatement();	// The object used to run a static SQL statement and returning the results it produces.
			newRows = sentence.executeUpdate(query);			// SQL: executed!
			rowsInserted += newRows;
			
			if (newRows > 0) {
				System.out.println("\t" + rowsInserted + "\tRegistry inserted!");
			}
			
			sentence.close();
			
		} catch (SQLException e) {
			System.err.println("SQL exception in the insertion.");
			System.err.printf("Message  : %s %n", e.getMessage());
			System.err.printf("SQL state: %s %n", e.getSQLState());
			System.err.printf("Cod error: %s %n", e.getErrorCode());
		}
		return rowsInserted;
		
	}
	
}